### ISSUE TITLE
Genel - Eline sağlık 🎉 

### ISSUE THREAD

**Issue by VB10** [HasancanCakicioglu/Solution_Challenge_2023_FikirAtlasi#17]
Projeye şöyle bir göz gezdirdiğimde genel olarak bir yaklaşım olduğunu gördüm bu güzel bir kaç noktaya değinmek isterim

- bu injection katmanlarını koda girip bakmadım ama çok fazla var ve ben buna genel olarak hep ihityacı olan yere ihtiyacı olan sınıfı verme taraftarıyım ondan dolayı bu katmanlara bakmak gerekir
- birde sınıf içinde olmadan bir method yazılmasını çok sevmem ondan dolayı bunları daha toplu bir şekilde yönetebiliridk
- very good analyiss gerekiyor özellikle linter için
- klasörleme yapısı çok karışık ney nerede nasıl belilri olmuyor
- app inilzaatlize işlemleri başka bir dosyada parçalı yönetilebilir
https://github.com/HasancanCakicioglu/Solution_Challenge_2023_FikirAtlasi/blob/main/lib/feature/Splash/cubit/splash_finished_cubit.dart
https://github.com/HasancanCakicioglu/Solution_Challenge_2023_FikirAtlasi/blob/main/lib/feature/Onboard/presentation/cubit/onboard_cubit.dart

- view katmanların function component değil widget class olarak extreact edilmeli 
- localızaitonlar constlar olmalı
- bazı noktlarada try catch kullanımları merkezileştilreilbir
- json seriazalble kullanabilir
- format sorunları empty yerler var

tabi proje büyük olduğu için bazı noktlarada yine küçük sorunlar vs var ama bu projenin muhakkak unit testlerin de yazılamsını isterim usecase layerleri için onun dışında gayet güzel yeterli bir rpoje olmuş eline sağlık 🎉

**Comment by HasancanCakicioglu** [comment]
Çok teşekkürler hocam yapıcı eleştirileriniz için.
